export interface NavPage {
  path: string;
  title: string;
  /** One-line description shown under the H1 on the page itself. */
  description: string;
}

export interface NavGroup {
  /** Which guide the group belongs to; the sidebar shows a heading per guide. */
  section: "User guide" | "Developer guide";
  label: string;
  pages: NavPage[];
}

// The single source of truth for the site's structure: the left sidebar, the
// previous/next links at the bottom of every page, and the router's route list
// (src/main.tsx) are all generated by walking this list. Groups are split into
// a user guide (running and using the app) and a developer guide (internals,
// API, evaluation); URLs don't depend on which guide a page is in.
export const nav: NavGroup[] = [
  {
    section: "User guide",
    label: "Get started",
    pages: [
      { path: "/", title: "Overview", description: "Chat with your documents. Every model, vector and message stays on your machine." },
      { path: "/quickstart", title: "Quickstart", description: "Clone, start the stack, upload a file, and ask it a question — about ten minutes." },
      { path: "/using-the-app", title: "Using the app", description: "A tour of the chat app: conversations, streaming answers, sources and the Documents panel." },
    ],
  },
  {
    section: "User guide",
    label: "How it works",
    pages: [
      { path: "/how-it-works/ingestion", title: "Uploading & chunking", description: "What happens to a .txt, .md, .pdf or .docx file when you upload it." },
      { path: "/how-it-works/retrieval", title: "Finding the right passages", description: "How a question is matched to your documents, and when LocalCortex decides nothing matches." },
      { path: "/how-it-works/answering", title: "Answering", description: "What the model reads, how it's told to answer, and why it says so when it doesn't know." },
      { path: "/how-it-works/memory", title: "Follow-up questions", description: "How \"what about her projects?\" gets understood without repeating yourself." },
    ],
  },
  {
    section: "User guide",
    label: "Help",
    pages: [
      { path: "/reference/troubleshooting", title: "Troubleshooting", description: "Common problems, what causes them, and how to fix them." },
    ],
  },
  {
    section: "Developer guide",
    label: "Internals",
    pages: [
      { path: "/how-it-works/architecture", title: "Architecture", description: "How the web app, API, Ollama, Qdrant and Postgres fit together." },
      { path: "/reference/api", title: "HTTP API", description: "Every route: what to send, what comes back, and the status codes." },
      { path: "/reference/configuration", title: "Configuration", description: "Environment variables, their defaults, and which ones need a re-upload." },
    ],
  },
  {
    section: "Developer guide",
    label: "Evaluation",
    pages: [
      { path: "/evaluation/measuring-quality", title: "How quality is measured", description: "The test scripts, what each one checks, and the latest results." },
      { path: "/evaluation/what-we-tried", title: "What we tried", description: "Every experiment: what worked, what made things worse, and the numbers behind each decision." },
    ],
  },
  {
    section: "Developer guide",
    label: "Project",
    pages: [
      { path: "/project/roadmap", title: "Roadmap & contributing", description: "What's next, how to run the tests, and the project's conventions." },
      { path: "/project/contact", title: "Contact", description: "Questions, feedback or ideas: get in touch." },
    ],
  },
];

export const flatPages: NavPage[] = nav.flatMap((g) => g.pages);

export function findGroup(path: string): NavGroup | undefined {
  return nav.find((g) => g.pages.some((p) => p.path === path));
}

export function findPage(path: string): NavPage | undefined {
  return flatPages.find((p) => p.path === path);
}

export function prevNext(path: string): { prev?: NavPage; next?: NavPage } {
  const i = flatPages.findIndex((p) => p.path === path);
  if (i === -1) return {};
  return { prev: flatPages[i - 1], next: flatPages[i + 1] };
}

export const GITHUB_URL = "https://github.com/Sekharendu/LocalCortex";
